export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const REQUEST_REALTY_INFO = 'REQUEST_REALTY_INFO';
export const REALTY_INFO_SUCCESS = 'REALTY_INFO_SUCCESS';
export const REALTY_INFO_ERROR = 'REALTY_INFO_ERROR';
